### ISSUE TITLE
Why do we have mixpanel-py as dependency rather than mixpanel-python?

### ISSUE THREAD

**Issue by ashwch** [jessepollak/mixpanel-python-async#11]
[mixpanel-py](https://pypi.python.org/pypi/mixpanel-py) has been deprecated, is there a reason for why we are still using it instead of the official [mixpanel-python](https://pypi.python.org/pypi/mixpanel) library?

**Comment by jessepollak** [comment]
No reason at all — would be happy to accept a PR with the change, or I'll get to it sooner or later :)

**Comment by ashwch** [comment]
Done, please check and merge: https://github.com/jessepollak/mixpanel-python-async/pull/12

**Comment by jessepollak** [comment]
Awesome, thank you!
