### ISSUE TITLE
Parameter api_host is not passed to the BufferedConsumer

### ISSUE THREAD

**Issue by kimmoahola** [jessepollak/mixpanel-python-async#19]
Hello!

The parameter `api_host` is used when we want to use mixpanel's EU servers:

`consumer = AsyncBufferedConsumer(api_host="api-eu.mixpanel.com")`

That parameter is not passed to the mixpanel consumer when using AsyncBufferedConsumer.

There is also some other parameters not passed, like `request_timeout`, `verify_cert`, etc.

**Comment by kimmoahola** [comment]
@bbc2 Any chance you have time to look into this?

**Comment by bbc2** [comment]
Yes, I forgot I had commit rights here.  I made #20.  Does it look like it would solve your issue?

**Comment by kimmoahola** [comment]
I tested that branch and it works great!
